apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedupmyapp
  name: speedupmyapp
spec:
  selector:
    matchLabels:
      app: speedupmyapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: speedupmyapp
    spec:
      containers:
        - name: speedupmyapp
          image: eb129/speedupmyapp
          imagePullPolicy: Always
          command: ['npm', 'run', 'dev']
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 512M
            requests:
              cpu: 250m
              memory: 256M
